# Usar una imagen base de Python
FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 5000

# Definir el comando para ejecutar la aplicación
CMD ["python", "api_model_3.py"]